version: "3.9"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
